services:
  application:
    stdin_open: true
    tty: true
    container_name: ${_Values_root_name}-application
    image:  ${_Values_image_repository}:${_Values_image_tag}
    restart: 'no'
    ports:
      - "${_Values_service_port}:${_Values_service_port}"
    command: ["-Xmx${_Values_resources_requests_memory}"]

    healthcheck:
      test: "curl -f http://localhost:${_Values_service_port}/actuator/health || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - tmp:/tmp
      - applogs:/usr/share/logs
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      TZ: Europe/Berlin
      quarkus.http.port: "${_Values_service_port}"
      quarkus.http.io-threads: "20"

      #tracing
      quarkus.otel.exporter.otlp.traces.endpoint: "http://${_Values_host_docker_internal}:4317"
      quarkus.application.name: "agentic.quarkus"

      #langchain
      ANTHROPIC_FOUNDRY_API_KEY: ${ANTHROPIC_FOUNDRY_API_KEY}
      ANTHROPIC_FOUNDRY_RESOURCE: ${ANTHROPIC_FOUNDRY_RESOURCE}
      ANTHROPIC_DEFAULT_SONNET_MODEL: ${ANTHROPIC_DEFAULT_SONNET_MODEL}

      #mcp
      quarkus.langchain4j.mcp.callee.url: "http://${_Values_host_docker_internal}:50900/mcp"
      quarkus.langchain4j.mcp.person.url: "http://${_Values_host_docker_internal}:50800/mcp"


      #log levels
      QUARKUS_LOG_LEVEL: "INFO"
      QUARKUS_LOG_CATEGORY__ORG_GOAFABRIC__LEVEL: "INFO"
      QUARKUS_LOG_CATEGORY__ORG_FLYWAYDB_CORE__LEVEL: "INFO"
      QUARKUS_LOG_CATEGORY__ORG_HIBERNATE__LEVEL: "INFO"


    depends_on:
      postgres:
        condition: service_started

  postgres:
    container_name: ${_Values_root_name}-postgres
    image: postgres:18.3
    restart: 'no'
    ports:
      - 5432:5432
    environment:
      TZ: "Europe/Berlin"
      #secrets
      POSTGRES_USER: "person-service"
      POSTGRES_PASSWORD: "person-service"
      POSTGRES_DB: "person"

    command: postgres -c 'shared_buffers=64MB' -c 'max_connections=30' -c 'shared_preload_libraries=pg_stat_statements'
    healthcheck:
      test: "sh -c pg_isready"
      interval: 2s
      timeout: 5s
      retries: 5
#    volumes:
#      - pgdata_quarkus:/var/lib/postgresql/data
    networks:
      - ${_Values_root_name}-net


volumes:
    tmp:
    applogs:
    pgdata_quarkus:

networks:
  person-service-net:
    driver: bridge