#web
quarkus.application.name=callee-service
quarkus.http.port=50500
quarkus.http.io-threads=20
#quarkus.vertx.worker-pool-size=

#monitoring
quarkus.smallrye-health.root-path=/actuator/health
quarkus.smallrye-health.liveness-path=/actuator/health/liveness
quarkus.smallrye-health.readiness-path=/actuator/health/readiness
quarkus.micrometer.export.prometheus.path=/actuator/prometheus

#tracing
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.log.category."io.opentelemetry.exporter.internal".level=OFF

#logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p tenantId=%X{tenantId} [%X{traceId}] [%c{2.}] (%t) %s%e%n

quarkus.log.level=INFO
quarkus.log.category."org.goafabric".level=INFO
quarkus.log.category."org.flywaydb.core".level=INFO
quarkus.log.category."org.hibernate".level=INFO


#model config
quarkus.langchain4j.chat-model.provider=anthropic
#quarkus.langchain4j.chat-model.provider=openai

#ollama openai model
quarkus.langchain4j.openai.api-key=none
quarkus.langchain4j.openai.base-url=http://localhost:11434/v1
quarkus.langchain4j.openai.chat-model.model-name=gpt-oss:20b
quarkus.langchain4j.openai.chat-model.temperature=0.0
quarkus.langchain4j.openai.chat-model.timeout=60000

#claude model
quarkus.langchain4j.anthropic.api-key=${ANTHROPIC_FOUNDRY_API_KEY}
quarkus.langchain4j.anthropic.base-url=https://${ANTHROPIC_FOUNDRY_RESOURCE}.services.ai.azure.com/anthropic/v1
quarkus.langchain4j.anthropic.chat-model.model-name=${ANTHROPIC_DEFAULT_SONNET_MODEL}
quarkus.langchain4j.anthropic.chat-model.temperature=0.0

#mcp
quarkus.langchain4j.mcp.callee.transport-type=streamable-http
quarkus.langchain4j.mcp.callee.url=http://localhost:50900/mcp

#tools runner
tools.runner.enabled=true